[context.deploy-preview.environment]
   REACT_APP_BASE_URL = "https://api.werick.tk/api/v1"
   REACT_APP_PRODUCTION_URL = "https://werick.codes"
   REACT_APP_DISQUS_SHORTNAME="werick"
   REACT_APP_DISQUS_URL="werick.tk"
   

[context.production.environment]
   REACT_APP_BASE_URL = "https://api.werick.tk/api/v1"
   REACT_APP_PRODUCTION_URL = "https://werick.codes"
   REACT_APP_DISQUS_SHORTNAME="werick"
   REACT_APP_DISQUS_URL="werick.tk"
