import { Link } from "gatsby";
import PropTypes from "prop-types";
import React from "react";
import { Icon } from "antd";
// import MascotImages from "../../images/mascot.svg"
import "./index.css";

const Header = () => (
  <div>
    <header>
      <section>
        <nav>
          <ul>
            <li>
              <Link to="/">
                <img
                  src={
                    "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pgo8IURPQ1RZUEUgc3ZnIFBVQkxJ%0D%0AQyAiLS8vVzNDLy9EVEQgU1ZHIDIwMDEwOTA0Ly9FTiIKICJodHRwOi8vd3d3LnczLm9yZy9UUi8y%0D%0AMDAxL1JFQy1TVkctMjAwMTA5MDQvRFREL3N2ZzEwLmR0ZCI+CjxzdmcgdmVyc2lvbj0iMS4wIiB4%0D%0AbWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiB3aWR0aD0iMTIwMC4wMDAwMDBwdCIg%0D%0AaGVpZ2h0PSIxMjAwLjAwMDAwMHB0IiB2aWV3Qm94PSIwIDAgMTIwMC4wMDAwMDAgMTIwMC4wMDAw%0D%0AMDAiCiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCBtZWV0Ij4KICAgIDxtZXRhZGF0YT4K%0D%0AICAgIENyZWF0ZWQgYnkgcG90cmFjZSAxLjE1LCB3cml0dGVuIGJ5IFBldGVyIFNlbGluZ2VyIDIw%0D%0AMDEtMjAxNwogICAgPC9tZXRhZGF0YT4KICAgIDxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAuMDAw%0D%0AMDAwLDEyMDAuMDAwMDAwKSBzY2FsZSgwLjEwMDAwMCwtMC4xMDAwMDApIgogICAgZmlsbD0iI2Zh%0D%0AZWJkNyIgc3Ryb2tlPSJub25lIj4KICAgICAgICA8cGF0aCBkPSJNNDI2NCA5Njc3IGMtMjE3IC0x%0D%0ANjUgLTIxOCAtMTY1IC0zOTcgLTMxMCAtNzg2IC02MzYgLTEyMzQgLTEyMjMKICAgICAgICAtMTQw%0D%0ANSAtMTg0MiAtNjIgLTIyNSAtNzYgLTMzNSAtNzcgLTYwNSAwIC0yNTUgNyAtMzI1IDU2IC01MjUg%0D%0AMTQ3IC02MDIgNTUzCiAgICAgICAgLTEwNzkgMTA2NSAtMTI1MyAxNjcgLTU3IDI4MCAtNzUgNDY0%0D%0AIC03NiAxOTQgMCAyOTggMTYgNDcxIDc0IDY1MCAyMTYgMTEzOAogICAgICAgIDg0NSAxMjYxIDE2%0D%0AMjQgMjYgMTY3IDI4IDQ4NSA0IDY1MSAtOTIgNjM3IC00MDcgMTI4OCAtMTA0NiAyMTYwIC03MyA5%0D%0AOSAtMTQ0CiAgICAgICAgMTk3IC0xNTkgMjE3IC0xNCAyMSAtMjggMzcgLTMxIDM3IC0zIDAgLTk1%0D%0AIC02OCAtMjA2IC0xNTJ6IG0xMDMyIC0yNTIyIGM5NAogICAgICAgIC01NCAxNjIgLTE2MSAyMDYg%0D%0ALTMyNSAyMCAtNzUgMjMgLTEwOCAyMyAtMjc1IDAgLTE1NCAtMyAtMTk5IC0xNyAtMjQwIC0xMAog%0D%0AICAgICAgIC0yNyAtMjUgLTg2IC0zNCAtMTMwIC0zNyAtMTg3IC0xMDkgLTMyMyAtMjMxIC00Mzcg%0D%0ALTgwIC03NCAtMTI0IC05MiAtMjE5IC05MwogICAgICAgIC03MiAwIC04NSAzIC0xMzAgMzAgLTE0%0D%0AMSA4OCAtMjU2IDM2NSAtMzkzIDk1NSAtMzIgMTM0IC05MiA0MjMgLTg5IDQyNiAyIDEKICAgICAg%0D%0AICA0NyAtNTMgMTAwIC0xMTkgMjQ5IC0zMTQgNDA4IC00MzggNTAwIC0zOTEgNTYgMjkgODEgMTEy%0D%0AIDEwMyAzMzkgMjkgMjkxIDU2CiAgICAgICAgMzMwIDE4MSAyNjB6Ii8+CiAgICAgICAgPHBhdGgg%0D%0AZD0iTTcxOTkgODk5NyBjLTE2NSAtMTIxIC0zNTMgLTI2NyAtNDY0IC0zNjIgLTEyMyAtMTA1IC0z%0D%0ANDIgLTMyMSAtNDMyCiAgICAgICAgLTQyNyAtNDM3IC01MTQgLTU3NCAtMTA5NSAtMzkzIC0xNjU4%0D%0AIDczIC0yMjggMjQ1IC00NzIgNDI5IC02MTAgNDM5IC0zMjkKICAgICAgICAxMDM1IC0yNjIgMTQz%0D%0ANiAxNjEgMjU2IDI3MCAzOTUgNjA3IDQxMiA5OTkgMjEgNDc0IC0xNjMgOTcwIC01OTkgMTYyMCAt%0D%0AMTQ1CiAgICAgICAgMjE2IC0yNTIgMzY5IC0yNTggMzY5IC0zIDAgLTYyIC00MSAtMTMxIC05Mnog%0D%0AbS02NDQgLTE5OTEgYzE2NiAtOTggMjEwIC00NzIKICAgICAgICA4OCAtNzUwIC03MiAtMTY1IC0x%0D%0ANzggLTI1OSAtMjkwIC0yNTkgLTE1NiAwIC0yNTQgMTk0IC0zMDggNjExIC05IDY4IC0xNSAxMzkK%0D%0AICAgICAgICAtMTMgMTU3IGwzIDM1IDYyIC04NSBjNjggLTkzIDEzMSAtMTQ1IDE3NCAtMTQ1IDIy%0D%0AIDAgMzQgOSA1MyAzOCAyOCA0MyAzOSA4MAogICAgICAgIDY1IDIyNSAxMSA1OCAyOCAxMjYgMzkg%0D%0AMTUxIDE5IDQxIDI0IDQ2IDUzIDQ2IDE4IDAgNTEgLTExIDc0IC0yNHoiLz4KICAgICAgICA8cGF0%0D%0AaCBkPSJNODU3MCA1OTYwIGMtMTQ2IC0zNyAtNTA4IC0xMjkgLTgwNSAtMjA1IC0yOTcgLTc1IC02%0D%0ANzAgLTE3MCAtODMwCiAgICAgICAgLTIxMCAtMTU5IC00MSAtNDYxIC0xMTcgLTY3MCAtMTcwIC0y%0D%0AMDkgLTUzIC01MjggLTEzNCAtNzEwIC0xODAgLTE4MSAtNDYKICAgICAgICAtNDkyIC0xMjUgLTY5%0D%0AMCAtMTc1IC0xOTggLTUwIC01MjYgLTEzMyAtNzMwIC0xODUgLTIwMyAtNTIgLTUzMCAtMTM0IC03%0D%0AMjUKICAgICAgICAtMTg0IC0xMTE5IC0yODMgLTEzMTYgLTMzNCAtMTMyOCAtMzQwIC05IC01IDEw%0D%0AIC0yNSA2MiAtNjUgbDc1IC01OCAxNjggMzYKICAgICAgICBjMTg5IDQxIDEzMDAgMjgwIDE0MDgg%0D%0AMzAzIDE1MSAzMiAxMTcxIDI1MSAxMzE1IDI4MyA1MiAxMSAxMjQgMjcgMTYwIDM1IDY4MAogICAg%0D%0AICAgIDE0NiAxMTE3IDI0MCAxMTY1IDI1MCAzMyA4IDMyMyA3MCA2NDUgMTM5IDMyMiA2OSA4NTcg%0D%0AMTg0IDExOTAgMjU2IDMzMyA3MgogICAgICAgIDYyNSAxMzUgNjUwIDE0MCAyNSA1IDg2IDE4IDEz%0D%0ANSAyOSA1MCAxMSAxNTkgMzQgMjQzIDUyIDgzIDE4IDE1MiAzNiAxNTIgNDEgMAogICAgICAgIDQg%0D%0ALTQgOCAtOSA4IC01IDAgLTE0MyA2MSAtMzA2IDEzNSAtMTYzIDc0IC0yOTcgMTM1IC0yOTggMTM0%0D%0AIC0xIDAgLTEyMSAtMzEKICAgICAgICAtMjY3IC02OXoiLz4KICAgIDwvZz4KPC9zdmc+"
                  }
                  alt="mascot-logo"
                  className="logo"
                  style={{ width: 55 + "px" }}
                />
              </Link>
            </li>
            <li>
              <Link to="/about">
                <Icon type="info" style={{ fontSize: "3.3rem" }} />
              </Link>
            </li>
            <li>
              <Link to="/search">
                <Icon type="search" style={{ fontSize: "3.3rem" }} />
              </Link>
            </li>
            <li>
              <a
                target="_blank"
                href="https://me.werick.codes"
                rel="noopener noreferrer"
              >
                <Icon type="user" style={{ fontSize: "3.3rem" }} />
              </a>
            </li>
          </ul>
        </nav>
      </section>
    </header>
  </div>
);

Header.propTypes = {
  siteTitle: PropTypes.string
};

Header.defaultProps = {
  siteTitle: ``
};

export default Header;
